"""Scraper modules for Defence, Railways, Scientific/IT, Banking, PSU, SSC/UPSC, State, and Apprenticeship portals."""

from typing import List
from datetime import datetime
from ..database.models import JobRecord
from .base_scraper import BaseScraper

TODAY_STR = "01/10/2026"


class DefenceScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Indian Army",
                department="Directorate General of Recruiting",
                recruitment_name="TGC-145 (Technical Graduate Course - July 2027)",
                post_name="Lieutenant (Permanent Commission - Technical)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.E./B.Tech in Computer Science & Engineering / IT explicitly listed as an eligible branch (final year / passout).",
                degree_requirement="B.E. / B.Tech in specified Engineering streams",
                branch_requirement="Computer Science & Engineering / Computer Technology / Info Tech",
                experience_requirement="None (Fresher / Final Year Eligible)",
                age_min=20,
                age_max=27,
                ews_applicable="YES (Standard Armed Forces rules)",
                vacancies=30,
                salary="₹56,100 – ₹1,77,500 + MSP ₹15,500/month",
                pay_level="Level 10 (Defence Pay Matrix)",
                application_start="2026-09-30",
                application_end="2026-10-29",
                exam_date="Direct SSB Interview (Jan – March 2027)",
                notification_date="2026-09-30",
                status="OPEN_NOW",
                selection_process="Engineering Marks Shortlisting → 5-Day SSB Interview → Medical Examination",
                exam_pattern="No written exam. Selection via Service Selection Board (SSB) Stage I (Screening) & Stage II (Psychology, GTO, Interview)",
                syllabus="SSB: OIR (Verbal/Non-Verbal Reasoning), PPDT, TAT, WAT, SRT, Group Discussions, Personal Interview",
                cutoff_previous_year="Cutoff typically 74% - 78% cumulative aggregate in Engineering semesters",
                official_notification_url="https://joinindianarmy.nic.in",
                official_application_url="https://joinindianarmy.nic.in/login.htm",
                source_url="https://joinindianarmy.nic.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Indian Navy",
                department="Directorate of Manpower Planning and Recruitment",
                recruitment_name="SSC Executive (Information Technology) - July 2027 Course",
                post_name="Sub Lieutenant (Executive Branch - IT)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech CSE/IT with minimum 60% marks and 60% marks in English (Class 10/12) is the primary required qualification.",
                degree_requirement="B.E. / B.Tech in CSE / IT / Software Systems / MCA",
                branch_requirement="Computer Science & Engineering / IT",
                experience_requirement="None (Fresher Eligible)",
                age_min=19,
                age_max=25,
                ews_applicable="YES",
                vacancies=18,
                salary="₹56,100 – ₹1,77,500 + MSP ₹15,500 + Allowances",
                pay_level="Level 10",
                application_start="2026-11-15",
                application_end="2026-12-05",
                exam_date="SSB Interviews (Feb – April 2027)",
                notification_date="Expected November 2026",
                status="UPCOMING",
                selection_process="Shortlisting based on B.Tech normalized marks → SSB Interview → Medicals",
                exam_pattern="Direct SSB Interview (No written exam fee)",
                syllabus="SSB Psychology tests, Group Testing Tasks, Personal Interview, Officer Intelligence Rating",
                cutoff_previous_year="Shortlisting cutoff ~72% - 76% in B.Tech",
                official_notification_url="https://www.joinindiannavy.gov.in",
                official_application_url="https://www.joinindiannavy.gov.in/en/account/login",
                source_url="https://www.joinindiannavy.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Indian Air Force",
                department="AFCAT Cell / C-DAC",
                recruitment_name="AFCAT 01/2027 (Air Force Common Admission Test)",
                post_name="Flying Branch & Ground Duty (Technical - Computer/IT)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech CSE candidates with min 60% marks are eligible for Aeronautical Engineer (Electronics/IT) and Non-Tech Admin branches.",
                degree_requirement="B.E. / B.Tech (min 60% marks) + 50% in Math & Physics at 10+2",
                branch_requirement="Computer Science & Engineering / Information Technology / Electronics",
                experience_requirement="None (Fresher Eligible)",
                age_min=20,
                age_max=26,
                ews_applicable="No reservation in officer cadre",
                vacancies=317,
                salary="₹56,100 – ₹1,77,500 + MSP ₹15,500/month",
                pay_level="Level 10",
                application_start="2026-12-01",
                application_end="2026-12-30",
                exam_date="February 2027",
                notification_date="Expected late November 2026",
                status="UPCOMING",
                selection_process="AFCAT Written Examination → EKT (Engineering Knowledge Test for Tech) → AFSB Interview",
                exam_pattern="100 Questions (300 Marks): General Awareness, Verbal Ability in English, Numerical Ability, Reasoning and Military Aptitude",
                syllabus="Quant (Arithmetic, Algebra, Percentages), Reasoning, English Comprehension, General Knowledge + Computer Architecture, Networks, OS for EKT",
                cutoff_previous_year="AFCAT cut-off: 137–155 marks out of 300",
                official_notification_url="https://afcat.cdac.in/AFCAT/",
                official_application_url="https://afcat.cdac.in/afcatreg/",
                source_url="https://afcat.cdac.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class RailwayScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Railway Recruitment Boards (RRB)",
                department="Ministry of Railways, Govt of India",
                recruitment_name="RRB NTPC Graduate Level (CEN No. 06/2026)",
                post_name="Station Master, Goods Train Manager, Senior Commercial cum Ticket Clerk",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Graduation in ANY discipline from a recognized University (B.Tech CSE qualifies 100%).",
                degree_requirement="Bachelor's Degree in any discipline",
                branch_requirement="Any recognized degree (CSE fully eligible)",
                experience_requirement="None (Fresher Eligible)",
                age_min=18,
                age_max=33,
                ews_applicable="YES (10% reservation, separate cutoff)",
                vacancies=3477,
                salary="₹29,200 – ₹35,400 basic + DA + HRA (Gross ~₹52,000 – ₹65,000)",
                pay_level="Level 5 & Level 6",
                application_start="2026-10-08",
                application_end="2026-11-06",
                exam_date="December 2026 – January 2027 (Tentative)",
                notification_date="2026-10-07",
                status="OPENING_SOON",
                selection_process="CBT-1 (Screening) → CBT-2 (Merit) → CBAT (Aptitude test for Station Master) / Typing Test → Document Verification & Medical",
                exam_pattern="CBT-1: 100 Qs (90 mins) [GA: 40, Math: 30, Reasoning: 30]. CBT-2: 120 Qs (90 mins) [GA: 50, Math: 35, Reasoning: 35]",
                syllabus="Maths (Number system, BODMAS, Algebra, Geometry, Trigonometry, SI/CI, Profit-Loss), General Intelligence & Reasoning, General Awareness (Current events, History, Geography, Polity, Science)",
                cutoff_previous_year="Level 6 (SM): UR 68–74, EWS 62–67, OBC 65–70 (Normalized marks out of 100 in CBT-2)",
                official_notification_url="https://www.rrbapply.gov.in",
                official_application_url="https://www.rrbapply.gov.in/#/auth/home",
                source_url="https://www.rrbapply.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Railway Recruitment Boards (RRB)",
                department="Ministry of Railways, Govt of India",
                recruitment_name="RRB Junior Engineer (JE) (CEN No. 04/2026)",
                post_name="Junior Engineer (Information Technology / Track Machine / Electronics)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech Computer Science & Engineering / IT is explicitly included in the Electronics & Allied Engineering exam group.",
                degree_requirement="B.E. / B.Tech or 3-year Diploma in Engineering",
                branch_requirement="Computer Science & Engineering / Computer Engineering / IT",
                experience_requirement="None (Fresher Eligible)",
                age_min=18,
                age_max=36,
                ews_applicable="YES",
                vacancies=4029,
                salary="₹35,400 basic + DA + allowances (Gross ~₹58,000 - ₹66,000)",
                pay_level="Level 6",
                application_start="2026-08-14",
                application_end="2026-09-13",
                exam_date="CBT-1: 27, 28, and 30 October 2026",
                notification_date="2026-08-13",
                status="CLOSED",
                selection_process="CBT-1 → CBT-2 (Technical Paper) → Document Verification & Medical",
                exam_pattern="CBT-1: 100 Qs (90 min) [Math 30, Reasoning 25, Gen Science 30, GA 15]. CBT-2: 150 Qs [Technical Abilities 100, Physics/Chem 15, Basics of Computers 10, Environment 10, GA 15]",
                syllabus="CBT-2 Technical: Digital Electronics, Microprocessors, Computer Networks, Operating Systems, C/C++ Programming, Database Systems, Web Technologies",
                cutoff_previous_year="CBT-1: UR 64–72, EWS 56–62, OBC 60–68",
                official_notification_url="https://www.rrbapply.gov.in",
                official_application_url="https://www.rrbapply.gov.in",
                source_url="https://www.rrbapply.gov.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class ApprenticeScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="DRDO - Proof & Experimental Establishment (PXE), Chandipur",
                department="Department of Defence R&D, Ministry of Defence",
                recruitment_name="Graduate Apprentice Recruitment 2026-27",
                post_name="Graduate Apprentice (Computer Science & Engineering)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech in Computer Science & Engineering explicitly accepted for 1-year graduate apprenticeship under Apprentices Act.",
                degree_requirement="B.E. / B.Tech in CSE / IT with minimum 60% marks",
                branch_requirement="Computer Science & Engineering",
                experience_requirement="None (Must be fresher passout / no previous apprenticeship)",
                age_min=18,
                age_max=27,
                ews_applicable="YES",
                vacancies=15,
                salary="₹9,000/month (Stipend as per MHRD NATS norms)",
                pay_level="Graduate Apprentice Stipend",
                application_start="2026-09-15",
                application_end="2026-10-12",
                exam_date="Merit shortlisting based on B.Tech aggregate marks",
                notification_date="2026-09-15",
                status="OPEN_NOW",
                selection_process="Merit screening on degree marks → Document Verification at Chandipur, Balasore, Odisha",
                exam_pattern="Direct merit selection (No written examination)",
                syllabus="Not applicable (Evaluation based on engineering coursework and project viva)",
                cutoff_previous_year="Merit cutoff typically ~75%+ in B.Tech",
                official_notification_url="https://www.drdo.gov.in/careers",
                official_application_url="https://www.drdo.gov.in (Offline typed form sent to Director, PXE Chandipur, Balasore, Odisha- 756025)",
                source_url="https://www.drdo.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Canara Bank",
                department="Human Resources Division (under NATS)",
                recruitment_name="Canara Bank Graduate Apprentice Engagement 2026-27",
                post_name="Graduate Apprentice",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Degree in ANY discipline (B.Tech CSE fully eligible) from a recognized university. Registered on NATS 2.0 portal.",
                degree_requirement="Bachelor's Degree in any discipline (B.Tech CSE qualifies)",
                branch_requirement="Any recognized graduation branch",
                experience_requirement="None (Must not have undergone prior apprenticeship training)",
                age_min=20,
                age_max=28,
                ews_applicable="YES",
                vacancies=3500,
                salary="₹15,000/month (₹10,500 Bank share + ₹4,500 Govt DBT via NATS)",
                pay_level="Stipendiary Trainee",
                application_start="2026-09-21",
                application_end="2026-10-17",
                exam_date="Online Test / Merit Verification (November 2026)",
                notification_date="2026-09-20",
                status="OPEN_NOW",
                selection_process="Merit evaluation / Online test on basic reasoning & quant + Local language proficiency test",
                exam_pattern="Short test on General Awareness, English, Reasoning & Computer Literacy",
                syllabus="Basic Aptitude, Reasoning, Banking Awareness, Computer Fundamentals",
                cutoff_previous_year="State-wise merit lists based on graduation percentages",
                official_notification_url="https://canarabank.com/pages/careers-recruitment",
                official_application_url="https://nats.education.gov.in",
                source_url="https://nats.education.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Steel Authority of India Limited (SAIL) - Bhilai Steel Plant",
                department="Bhilai Steel Plant Human Resources",
                recruitment_name="SAIL BSP Graduate Apprenticeship 2026",
                post_name="Graduate Engineer Apprentice (Computer Science)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="Degree in Computer Science Engineering explicitly notified for apprenticeship training with PSU experience certificate.",
                degree_requirement="B.E. / B.Tech in CSE / IT from AICTE approved institution",
                branch_requirement="Computer Science & Engineering",
                experience_requirement="None (Fresher only)",
                age_min=18,
                age_max=28,
                ews_applicable="YES",
                vacancies=30,
                salary="₹9,000/month + free medical treatment in Plant hospital",
                pay_level="Apprentice Stipend",
                application_start="2026-09-25",
                application_end="2026-10-20",
                exam_date="Walk-in Selection: 10 to 12 November 2026 at Bhilai",
                notification_date="2026-09-24",
                status="OPEN_NOW",
                selection_process="NATS Portal Application → Walk-in Interview / Document Verification at Bhilai, Chhattisgarh",
                exam_pattern="Personal interview / viva on fundamental CS subjects & B.Tech project",
                syllabus="Data Structures, DBMS, Networking, Web Technologies, Software Engineering",
                cutoff_previous_year="Interview performance + min 60% in B.Tech",
                official_notification_url="https://sail.co.in/en/careers",
                official_application_url="https://nats.education.gov.in",
                source_url="https://nats.education.gov.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class ScientificITScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Centre for Development of Advanced Computing (C-DAC)",
                department="C-DAC Guwahati / MeitY",
                recruitment_name="Advt. No. CINE/REC/2026/06",
                post_name="Project Engineer (Full Stack Developer / Network Security)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech in Computer Science / IT / Computer Engineering explicitly designated as qualifying degree for Software and Network roles.",
                degree_requirement="B.E. / B.Tech (min 60% marks) in Computer Science / IT / Electronics",
                branch_requirement="Computer Science & Engineering / Information Technology",
                experience_requirement="0–1 years (Fresher candidates with strong MERN/Java project work accepted)",
                age_min=21,
                age_max=30,
                ews_applicable="YES",
                vacancies=12,
                salary="₹30,000 – ₹45,000/month consolidated",
                pay_level="Consolidated Project Pay",
                application_start="2026-09-25",
                application_end="2026-10-09",
                exam_date="Walk-in Interviews daily 2:00 PM – 6:00 PM (Monday to Friday until Oct 9)",
                notification_date="2026-09-24",
                status="OPEN_NOW",
                selection_process="Walk-in Document Verification & Technical Interview at IIT Guwahati Research Park",
                exam_pattern="Direct Technical Interview testing Full Stack Development, REST APIs, Databases, and Architecture",
                syllabus="JavaScript, React, Node.js, Express, MongoDB, SQL queries, RESTful services, Git, System Design basics",
                cutoff_previous_year="Performance in technical panel interview",
                official_notification_url="https://www.cdac.in",
                official_application_url="https://www.cdac.in/index.aspx?id=job_guwahati_sept26",
                source_url="https://www.cdac.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="National Informatics Centre (NIC) / NIELIT",
                department="Ministry of Electronics and Information Technology (MeitY)",
                recruitment_name="Advt. No. NIC/SCB/2026/1",
                post_name="Scientist 'B' (Group A Gazetted - CS/IT)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.E./B.Tech in Computer Science / Computer Engineering / IT is the primary qualification.",
                degree_requirement="B.E. / B.Tech in CSE / IT or MCA or M.Sc Computer Science",
                branch_requirement="Computer Science & Engineering / Information Technology",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=30,
                ews_applicable="YES (EWS reservation with age/merit provisions)",
                vacancies=243,
                salary="₹56,100 – ₹1,77,500 (Gross ~₹90,000 – ₹1,05,000/month)",
                pay_level="Level 10 (7th CPC Group A Gazetted)",
                application_start="2026-04-10",
                application_end="2026-05-15",
                exam_date="Revised Shortlist Announcement Expected in October 2026",
                notification_date="2026-04-05",
                status="RESULT_PENDING",
                selection_process="GATE CS score shortlisting (1:3 ratio) followed by Personal Interview before MeitY Board",
                exam_pattern="Personal Technical Interview (85% GATE score weightage + 15% Interview marks)",
                syllabus="Operating Systems, DBMS, Computer Networks, Data Structures & Algorithms, Theory of Computation, Web Security, Cloud Computing",
                cutoff_previous_year="GATE Score Cutoff: UR ~620+, EWS ~570+, OBC ~585+",
                official_notification_url="https://recruitment.nic.in",
                official_application_url="https://recruitment.nic.in",
                source_url="https://recruitment.nic.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Indian Space Research Organisation (ISRO)",
                department="Department of Space, Govt of India",
                recruitment_name="ISRO Centralised Recruitment Board (ICRB) 2026-27",
                post_name="Scientist/Engineer 'SC' (Computer Science)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech in Computer Science & Engineering with minimum 65% marks or 6.84 CGPA is specifically eligible.",
                degree_requirement="B.E. / B.Tech in Computer Science & Engineering with First Class",
                branch_requirement="Computer Science & Engineering",
                experience_requirement="None (Fresher / Final Year Eligible)",
                age_min=21,
                age_max=28,
                ews_applicable="YES",
                vacancies=45,
                salary="₹56,100 – ₹1,77,500 (Gross ~₹90,000 – ₹1,05,000/month + Space HRA/Lease)",
                pay_level="Level 10",
                application_start="2026-11-20",
                application_end="2026-12-20",
                exam_date="Written Examination / ICRB Exam (February 2027)",
                notification_date="Expected November 2026",
                status="UPCOMING",
                selection_process="Written Examination (80 marks technical + 20 marks aptitude) → Interview (min 60% to qualify)",
                exam_pattern="Part A: 80 Discipline-specific MCQs (75% core CS + 25% allied). Part B: 15 Aptitude questions (20 marks). Penalty 0.33 for wrong answer.",
                syllabus="Core CS: Algorithms, Data Structures, Compiler Design, OS, DBMS, Computer Networks, Computer Architecture, Discrete Mathematics, Digital Logic",
                cutoff_previous_year="Written Cutoff: UR ~56–62/100, EWS ~50–55/100, OBC ~52–58/100",
                official_notification_url="https://www.isro.gov.in/Careers.html",
                official_application_url="https://www.isro.gov.in/Careers.html",
                source_url="https://www.isro.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="DRDO - Recruitment & Assessment Centre (RAC)",
                department="Department of Defence R&D, Ministry of Defence",
                recruitment_name="Scientist 'B' Recruitment (Advt. No. 158 / 2026-27)",
                post_name="Scientist 'B' (Computer Science & Engineering)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="First class B.Tech in Computer Science & Engineering is the fundamental qualification.",
                degree_requirement="First Class B.E. / B.Tech in Computer Science & Engineering",
                branch_requirement="Computer Science & Engineering",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=28,
                ews_applicable="YES",
                vacancies=40,
                salary="₹56,100 – ₹1,77,500 + Defence Special Allowances",
                pay_level="Level 10 (Group A Gazetted)",
                application_start="2026-12-10",
                application_end="2027-01-10",
                exam_date="Direct Personal Interview (March – April 2027)",
                notification_date="Expected December 2026",
                status="UPCOMING",
                selection_process="GATE CS Score Shortlisting (1:5 ratio) → Personal Interview before RAC Board at Delhi",
                exam_pattern="Interview carries 100 marks (minimum qualifying 70% for UR). Merit is 80% GATE Score + 20% Interview marks.",
                syllabus="B.Tech Computer Science Core: Algorithms, Operating Systems, Networks, Database Systems, Computer Security, Software Engineering, AI basics",
                cutoff_previous_year="GATE CS Score Cutoff for Shortlisting: UR ~660+, EWS ~605+, OBC ~625+",
                official_notification_url="https://rac.gov.in",
                official_application_url="https://rac.gov.in",
                source_url="https://rac.gov.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class BankingScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="State Bank of India (SBI)",
                department="Central Recruitment & Promotion Department (CRPD)",
                recruitment_name="Specialist Cadre Officers (CRPD/SCO/2026-27/24 & 25)",
                post_name="Specialist Officer (Digital Marketing / Systems / IT)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech in Computer Science / IT accepted for specialized technology & digital transformation roles.",
                degree_requirement="B.E. / B.Tech in CS / IT or MCA / MBA Tech",
                branch_requirement="Computer Science / IT",
                experience_requirement="Varies by post (0–2 years for entry specialist roles)",
                age_min=21,
                age_max=32,
                ews_applicable="YES",
                vacancies=185,
                salary="₹48,170 – ₹89,890 + Bank allowances (CTC ~₹14–18 Lakhs/annum)",
                pay_level="JMGS-I / MMGS-II",
                application_start="2026-09-30",
                application_end="2026-10-21",
                exam_date="Shortlisting & Personal Interview (November 2026)",
                notification_date="2026-09-29",
                status="OPEN_NOW",
                selection_process="Shortlisting based on qualification & profile → Personal Interview",
                exam_pattern="Direct Interview or Online Technical Assessment",
                syllabus="Web technologies, Digital platforms, APIs, Cloud basics, System Architecture, Database handling",
                cutoff_previous_year="Interview qualifying marks 40% for UR, 35% for reserved",
                official_notification_url="https://sbi.bank.in/web/careers/current-openings",
                official_application_url="https://sbi.bank.in/web/careers/current-openings",
                source_url="https://sbi.bank.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Securities and Exchange Board of India (SEBI)",
                department="Information Technology Department",
                recruitment_name="SEBI Officer Grade A (Assistant Manager) - IT Stream 2026",
                post_name="Assistant Manager (Information Technology)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.Tech in ANY engineering branch or B.Tech in Computer Science/IT or MCA is explicitly specified.",
                degree_requirement="Bachelor's Degree in Engineering (any branch) OR MCA OR Master's in CS/IT",
                branch_requirement="Computer Science / IT / Any Engineering branch",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=30,
                ews_applicable="YES (EWS reservation in Officer Grade A)",
                vacancies=34,
                salary="₹44,500 – ₹89,150 (Total Monthly Emoluments ~₹1,50,000 without accommodation)",
                pay_level="SEBI Grade A Officer",
                application_start="2026-10-25",
                application_end="2026-11-20",
                exam_date="Phase 1: December 2026; Phase 2: January 2027",
                notification_date="Expected October 2026",
                status="UPCOMING",
                selection_process="Phase 1 (Online Exam) → Phase 2 (Online Exam with Coding/Technical) → Phase 3 (Interview)",
                exam_pattern="Phase 1 Paper 2: 100 Marks on Specialized IT subjects. Phase 2 Paper 2: 100 Marks (Coding Test: Java/C++/Python + Technical Theory).",
                syllabus="Algorithms, Data Structures, OOP, SQL/RDBMS, Operating Systems, Computer Networks, Cyber Security, Software Engineering, Cloud Architecture",
                cutoff_previous_year="Phase 1 Paper 2 Cutoff: 40% (Fixed Qualifying). Phase 2 Aggregate Cutoff: UR ~65–70 marks out of 100",
                official_notification_url="https://www.sebi.gov.in",
                official_application_url="https://www.sebi.gov.in/sebiweb/other/career.jsp",
                source_url="https://www.sebi.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Institute of Banking Personnel Selection (IBPS)",
                department="Public Sector Banks Specialist Cadre",
                recruitment_name="IBPS SO (CRP SPL-XVII) - IT Officer Scale I",
                post_name="I.T. Officer (Scale I)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="4-year Engineering Degree in Computer Science / Computer Applications / IT / Electronics is the exact prescribed qualification.",
                degree_requirement="4-year B.Tech / B.E. in Computer Science / IT / Computer Engineering",
                branch_requirement="Computer Science & Engineering / Information Technology",
                experience_requirement="None (Fresher Eligible)",
                age_min=20,
                age_max=30,
                ews_applicable="YES",
                vacancies=380,
                salary="₹36,000 – ₹63,840 basic + DA + HRA (Gross ~₹56,000 – ₹64,000/month)",
                pay_level="JMGS-I",
                application_start="2027-06-25",
                application_end="2027-07-20",
                exam_date="Prelims: August 2027; Mains: November 2027",
                notification_date="Expected late June 2027 (SPL-XVI cycle currently ongoing)",
                status="UPCOMING",
                selection_process="Preliminary Exam → Main Exam (Professional Knowledge) → Common Interview",
                exam_pattern="Prelims: 150 Qs (125 Marks) [English 25, Reasoning 50, Quantitative Aptitude 50]. Mains: 60 Qs (60 Marks) in Professional Knowledge (CS/IT).",
                syllabus="Professional Knowledge: DBMS, Data Structures, Operating Systems, Computer Networks, Web Technologies, Network Security, Software Engineering, Object-Oriented Programming (Java/C++)",
                cutoff_previous_year="Mains Cutoff (out of 60): UR 14.50, EWS 11.25, OBC 13.75",
                official_notification_url="https://www.ibps.in",
                official_application_url="https://www.ibps.in",
                source_url="https://www.ibps.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class StateGovtScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Delhi Subordinate Services Selection Board (DSSSB)",
                department="Delhi District Courts / GNCTD",
                recruitment_name="Advt. No. 04/2026",
                post_name="Junior Judicial Assistant & Personal Assistant",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Graduation in ANY discipline from a recognized University (B.Tech CSE qualifies).",
                degree_requirement="Bachelor's Degree in any discipline",
                branch_requirement="Any recognized graduation branch",
                experience_requirement="None (Fresher Eligible)",
                age_min=18,
                age_max=27,
                ews_applicable="YES",
                vacancies=641,
                salary="₹29,200 – ₹92,300 + Delhi allowances (Gross ~₹48,000)",
                pay_level="Level 5",
                application_start="2026-10-06",
                application_end="2026-11-04",
                exam_date="December 2026 – January 2027",
                notification_date="2026-09-28",
                status="OPENING_SOON",
                selection_process="Tier-1 (MCQ Written Test) → Typing / Skill Test → Interview / Document Verification",
                exam_pattern="120 Questions (120 Marks): General English (60), General Knowledge (30), General Intelligence (30)",
                syllabus="English Grammar, Vocabulary, Comprehension, Current Affairs, Indian Constitution, Reasoning Ability",
                cutoff_previous_year="Tier 1 Cutoff: UR ~82/120, EWS ~74/120",
                official_notification_url="https://dsssb.delhi.gov.in",
                official_application_url="https://dsssbonline.nic.in",
                source_url="https://dsssb.delhi.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Bihar Public Service Commission (BPSC)",
                department="General Administration Department, Govt of Bihar",
                recruitment_name="BPSC Combined Competitive Examination (72nd CCE)",
                post_name="Sub-Divisional Officer, Block Development Officer, Revenue Officer",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Any graduate degree from a recognized university satisfies eligibility criteria.",
                degree_requirement="Bachelor's Degree in any discipline",
                branch_requirement="Any discipline (B.Tech CSE eligible)",
                experience_requirement="None (Fresher Eligible)",
                age_min=20,
                age_max=37,
                ews_applicable="YES (EWS certificate as per Bihar Govt norms)",
                vacancies=1920,
                salary="₹53,100 – ₹1,67,800 + Bihar State allowances",
                pay_level="Level 7 & Level 9",
                application_start="2026-06-15",
                application_end="2026-07-25",
                exam_date="Prelims Exam: 25 October 2026",
                notification_date="2026-06-10",
                status="CLOSED",
                selection_process="Preliminary Examination (150 Marks) → Mains Written Examination (900 Marks) → Interview (120 Marks)",
                exam_pattern="Prelims: 150 Objective Qs (Negative 1/3). General Studies, History, Geography, Indian Polity, Economy, General Science, Mental Ability",
                syllabus="History of India & Bihar, Indian National Movement, General Science, Bihar Geography, Indian Polity & Economy, Current Events",
                cutoff_previous_year="70th/71st CCE Prelims Cutoff: UR ~91.67, EWS ~86.33, BC ~88.00",
                official_notification_url="https://bpsc.bihar.gov.in",
                official_application_url="https://onlinebpsc.bihar.gov.in",
                source_url="https://bpsc.bihar.gov.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class PSUScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Bharat Electronics Limited (BEL)",
                department="Ghaziabad / Bengaluru Units",
                recruitment_name="BEL Trainee Engineer / Project Engineer (CS/IT)",
                post_name="Project Engineer - I (Computer Science)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="First class B.E./B.Tech in Computer Science / IT / Computer Engineering is required.",
                degree_requirement="B.E. / B.Tech in CSE / IT with minimum 55% marks (Pass class for SC/ST/PwBD)",
                branch_requirement="Computer Science & Engineering / Information Technology",
                experience_requirement="1-2 years experience for PE; 0 years (Fresher) for Trainee Engineer",
                age_min=21,
                age_max=28,
                ews_applicable="YES",
                vacancies=68,
                salary="₹40,000 – ₹55,000/month consolidated + medical & annual increments",
                pay_level="Contractual Engineer Band",
                application_start="2026-11-05",
                application_end="2026-11-26",
                exam_date="Written Test & Interview (December 2026)",
                notification_date="Expected early November 2026",
                status="UPCOMING",
                selection_process="Written Test (85% weightage) + Interview (15% weightage)",
                exam_pattern="100 MCQs (85 Technical CS + 15 General Aptitude)",
                syllabus="C/C++, Data Structures, OS, Networking, Software Engineering, Database Systems, Linux internals",
                cutoff_previous_year="Written Cutoff: UR ~68–74%",
                official_notification_url="https://bel-india.in/job-notifications/",
                official_application_url="https://bel-india.in/job-notifications/",
                source_url="https://bel-india.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Coal India Limited (CIL)",
                department="Systems Division",
                recruitment_name="Management Trainee (Systems / CS) 2026-27",
                post_name="Management Trainee (Systems)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="B.E./B.Tech in Computer Science / Computer Engineering / IT with minimum 60% marks.",
                degree_requirement="B.E. / B.Tech / MCA in Computer Science / IT",
                branch_requirement="Computer Science & Engineering / Information Technology",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=30,
                ews_applicable="YES",
                vacancies=55,
                salary="₹50,000 – ₹1,60,000 (E-2 Grade: Gross CTC ~₹16–18 Lakhs/year)",
                pay_level="E-2 Grade Executive",
                application_start="2026-11-10",
                application_end="2026-12-05",
                exam_date="Computer Based Test (January 2027)",
                notification_date="Expected late October 2026",
                status="UPCOMING",
                selection_process="Computer Based Test (CBT Paper 1 + Paper 2) → Document Verification & Medical",
                exam_pattern="Paper 1: 100 Qs [GA, Reasoning, Numerical Ability, English]. Paper 2: 100 Qs [Discipline Knowledge - Computer Science]",
                syllabus="Algorithms, OS, DBMS, Computer Networks, Software Engineering, Information Security, Web Development, Object-Oriented Concepts",
                cutoff_previous_year="CBT Cutoff: UR ~142/200, EWS ~128/200, OBC ~134/200",
                official_notification_url="https://www.coalindia.in/career",
                official_application_url="https://www.coalindia.in/career",
                source_url="https://www.coalindia.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Power Grid Corporation of India Limited (POWERGRID)",
                department="Corporate Telecom & IT",
                recruitment_name="Engineer Trainee (Computer Science) 2027",
                post_name="Engineer Trainee (CS)",
                category="technical",
                cse_eligible="YES",
                eligibility_reason="Full-time B.E./B.Tech in Computer Science / Computer Technology / IT with min 60% marks.",
                degree_requirement="B.Tech in CSE / IT with minimum 60% marks",
                branch_requirement="Computer Science / IT",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=28,
                ews_applicable="YES",
                vacancies=35,
                salary="₹40,000 – ₹1,40,000 (During training ₹40,000 basic; on regularization ₹50,000 basic; CTC ~₹15 Lakhs)",
                pay_level="E-1 Grade",
                application_start="2027-01-15",
                application_end="2027-02-15",
                exam_date="Based on GATE 2027 CS Score + Group Discussion & Interview",
                notification_date="Expected January 2027",
                status="UPCOMING",
                selection_process="GATE CS Normalized Score (85%) + Group Discussion (3%) + Personal Interview (12%)",
                exam_pattern="Direct shortlisting based on GATE 2027 Computer Science (CS) score",
                syllabus="GATE CS Syllabus: Discrete Maths, Digital Logic, COA, Programming & DS, Algorithms, TOC, Compiler, OS, DBMS, Networks",
                cutoff_previous_year="Shortlisting GATE Score: UR ~675+, EWS ~610+, OBC ~630+",
                official_notification_url="https://www.powergrid.in/careers",
                official_application_url="https://www.powergrid.in/careers",
                source_url="https://www.powergrid.in",
                last_verified=TODAY_STR
            )
        ]
        return records


class SSCUPSCScraper(BaseScraper):
    def scrape_or_load(self) -> List[JobRecord]:
        records = [
            JobRecord(
                organization="Staff Selection Commission (SSC)",
                department="DoPT / Various Central Ministries & Departments",
                recruitment_name="Combined Graduate Level (CGL) 2026-27",
                post_name="Assistant Section Officer, Inspector (Income Tax/GST/Customs), Sub-Inspector (CBI), Auditor",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Bachelor's Degree in ANY discipline from a recognized University (B.Tech CSE is 100% eligible for all general posts).",
                degree_requirement="Bachelor's Degree in any discipline",
                branch_requirement="Any recognized graduation branch",
                experience_requirement="None (Fresher Eligible)",
                age_min=18,
                age_max=32,
                ews_applicable="YES (EWS category reservation applicable across all posts)",
                vacancies=17727,
                salary="₹25,500 – ₹1,51,100 (Level 4: ₹40,000 gross; Level 7: ₹78,000 – ₹88,000 gross)",
                pay_level="Pay Level 4, 5, 6, 7 & 8",
                application_start="2026-06-24",
                application_end="2026-07-27",
                exam_date="Tier 1: 30 September – 30 October 2026 (Ongoing); Tier 2: January 2027",
                notification_date="2026-06-24",
                status="EXAM_PENDING",
                selection_process="Tier-I (Computer Based Qualifying) → Tier-II (Computer Based Scoring + Computer Knowledge + Data Entry Speed Test)",
                exam_pattern="Tier-I: 100 Qs (200 marks) [Reasoning 25, GA 25, Quant 25, English 25]. Tier-II: Paper 1 [Math 30, Reasoning 30, English 45, GA 25, Computer Knowledge 20 (Qualifying)] + Typing Test.",
                syllabus="Maths (Arithmetic + Advanced Maths: Geometry, Mensuration, Trigonometry, Algebra), Reasoning (Analogies, Coding, Syllogisms), English (Grammar, Vocab, Comprehension), General Awareness (History, Polity, Geography, Current Affairs, Science)",
                cutoff_previous_year="Tier-I Cutoff (out of 200 normalized): UR ~150–153, EWS ~143–145, OBC ~145–148, SC ~126, ST ~118",
                official_notification_url="https://ssc.gov.in",
                official_application_url="https://ssc.gov.in",
                source_url="https://ssc.gov.in",
                last_verified=TODAY_STR
            ),
            JobRecord(
                organization="Union Public Service Commission (UPSC)",
                department="DoPT / Govt of India",
                recruitment_name="Civil Services Examination (CSE) 2027",
                post_name="IAS, IPS, IFS, IRS, IRTS, Central Group A & B Services",
                category="non_technical",
                cse_eligible="YES",
                eligibility_reason="Any graduate degree from an incorporated university. Engineering graduates (CSE) are widely represented.",
                degree_requirement="Bachelor's Degree in any discipline",
                branch_requirement="Any recognized graduation branch",
                experience_requirement="None (Fresher Eligible)",
                age_min=21,
                age_max=32,
                ews_applicable="YES (EWS reservation & relaxations as per DoPT)",
                vacancies=1056,
                salary="₹56,100 – ₹2,50,000 (Junior Time Scale to Apex Level)",
                pay_level="Level 10 to Level 17",
                application_start="2027-02-10",
                application_end="2027-03-02",
                exam_date="Prelims: 23 May 2027; Mains: September 2027",
                notification_date="Expected 10 February 2027",
                status="UPCOMING",
                selection_process="Civil Services Prelims (GS Paper I + CSAT Paper II) → Mains Written Exam (9 Papers) → Personality Test (Interview)",
                exam_pattern="Prelims: GS I (200 marks - Merit) + CSAT II (200 marks - 33% qualifying). Mains: 7 Merit papers (1750 marks) + Interview (275 marks) = 2025 total.",
                syllabus="GS: History, Geography, Polity, Economy, Science & Tech, Environment, Current Events. CSAT: Comprehension, Logical Reasoning, Basic Numeracy. Mains Optional: Mathematics, Physics, or Humanities subjects.",
                cutoff_previous_year="Prelims GS Cutoff (out of 200): UR ~75.41, EWS ~68.02, OBC ~74.75, SC ~59.25, ST ~47.82",
                official_notification_url="https://upsc.gov.in",
                official_application_url="https://upsconline.nic.in",
                source_url="https://upsc.gov.in",
                last_verified=TODAY_STR
            )
        ]
        return records
